### PR TITLE
Add Authors

### PR DESCRIPTION
**Pull request by thetravisknight**

### CODE REVIEW

**Comment by Razza2018** [comment]
@k8-zali Are you okay with having your name added to this public repo?
This pull request is adding the authors of this repo to the bottom of the shortcut list.

**Comment by thetravisknight** [comment]
@Razza2018 @k8-zali I can always fully delete this branch and redo with usernames or just fully ditch it!

**Comment by Razza2018** [comment]
@thetravisknight We'll wait until Zali responds. I'm fine with having our names here. If your okay with it we can always just add our names but lets wait to merge this.

**Comment by thetravisknight** [comment]
@Razza2018 if we need to make any changes this branch needs to be removed without trace. A new branch then created so there is no history of the data we do not want

**Review by Razza2018 — APPROVED** [review]

**Pull request merged**
